-- Recipes seed (generated by scripts/recipesSeed.py — 8 Sep 2026).
-- Menu items + recipe lines for the bar costing engine, from the
-- costing sheet's machine-readable recipes. Idempotent: re-running
-- refreshes prices and replaces each item's lines.
begin;
-- clean up rows an earlier run seeded from placeholder data
delete from bar_recipe_lines where menu_item_id in (select id from bar_menu_items where lower(name) = lower('French Press Coffee'));
delete from bar_menu_items where lower(name) = lower('French Press Coffee');
delete from bar_recipe_lines where menu_item_id in (select id from bar_menu_items where lower(name) = lower('Pot of Tea'));
delete from bar_menu_items where lower(name) = lower('Pot of Tea');
delete from bar_recipe_lines where menu_item_id in (select id from bar_menu_items where lower(name) = lower('Hot Chocolate'));
delete from bar_menu_items where lower(name) = lower('Hot Chocolate');
-- Three MADE prep products (the mechanism bar_prep_recipes exists for):
-- their cost derives from what goes into a batch, never typed.
insert into bar_products (name, kind, category, source, base_unit, order_unit, order_to_base, count_unit, count_to_base, count_area, counted) values
  ('Fresh lime juice', 'prep', 'Prep', 'made', 'ml', 'batch', 1000, 'ml', 1, 'Back bar', false) on conflict ((lower(name))) do nothing;
insert into bar_products (name, kind, category, source, base_unit, order_unit, order_to_base, count_unit, count_to_base, count_area, counted) values
  ('Fresh lemon juice', 'prep', 'Prep', 'made', 'ml', 'batch', 1000, 'ml', 1, 'Back bar', false) on conflict ((lower(name))) do nothing;
insert into bar_products (name, kind, category, source, base_unit, order_unit, order_to_base, count_unit, count_to_base, count_area, counted) values
  ('Sugar syrup 1:1', 'prep', 'Prep', 'made', 'ml', 'batch', 750, 'ml', 1, 'Back bar', false) on conflict ((lower(name))) do nothing;
-- batch definitions: ~30ml juice per lime, ~35ml per lemon, 500g sugar -> 750ml syrup
insert into bar_prep_recipes (product_id, input_product_id, qty_base, makes_base)
  select p.id, i.id, 1, 30 from bar_products p, bar_products i where lower(p.name)='fresh lime juice' and lower(i.name)='limes'
  on conflict do nothing;
insert into bar_prep_recipes (product_id, input_product_id, qty_base, makes_base)
  select p.id, i.id, 1, 35 from bar_products p, bar_products i where lower(p.name)='fresh lemon juice' and lower(i.name)='lemons'
  on conflict do nothing;
insert into bar_prep_recipes (product_id, input_product_id, qty_base, makes_base)
  select p.id, i.id, 500, 750 from bar_products p, bar_products i where lower(p.name)='sugar syrup 1:1' and lower(i.name)='sugar (for house syrup)'
  on conflict do nothing;
insert into bar_menu_items (name, category, sell_price) values ('Camden Hells — Pint', 'draught', 7.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Camden Hells — Half', 'draught', 3.6)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Camden Hells — Jug', 'draught', 27.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Camden Stout', 'draught', 7.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Camden Stout — Half', 'draught', 3.6)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Five Points XPA — Pint', 'draught', 7.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Five Points XPA — Half', 'draught', 3.6)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Umbrella Cider — Pint', 'draught', 7.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Umbrella Cider — Half', 'draught', 3.6)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Corona', 'bottle', 4.8)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Asahi', 'bottle', 4.8)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Budweiser', 'bottle', 4.8)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Corona 0%', 'bottle', 4.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Big Drop Citra IPA 0.5%', 'bottle', 4.8)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Lucky Saint 0.5%', 'bottle', 4.8)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Cloudwater Fresh AF 0.5%', 'bottle', 6.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Oliver''s Fine Cider', 'bottle', 6.5)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Cheery Breeze Sour 4.5%', 'craft', 7.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Piccadilly Pilsner 4.2%', 'craft', 7.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Fresh AF Hazy IPA 0.5%', 'craft', 6.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Big Drop Paradiso Citra 0.5%', 'craft', 5.5)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Blanco Blanco — 125ml', 'wine', 7.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Blanco Blanco — Bottle', 'wine', 39.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Los Conejos Malditos — 125ml', 'wine', 7.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Los Conejos Malditos — Bottle', 'wine', 39.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Doom Juice Rose', 'wine', 7.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Doom Juice Rosé — Bottle', 'wine', 39.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Top Cuvee Orange — 125ml', 'wine', 7.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Top Cuvee Orange — Bottle', 'wine', 39.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Favonius Orange — Bottle', 'wine', 45.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Doom Juice Rouge — 125ml', 'wine', 7.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Doom Juice Rouge — Bottle', 'wine', 39.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Beaujolais Nouveau', 'wine', 45.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Chin Chin Vinho Verde — 125ml', 'wine', 7.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Chin Chin Vinho Verde — Bottle', 'wine', 35.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Cueva Nueva Vermut — Double (50ml)', 'wine', 6.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Cueva Nueva Vermut — Bottle (500ml)', 'wine', 50.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Prosecco — 125ml flute', 'wine', 7.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Prosecco', 'wine', 35.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Mini Prosecco 20cl', 'wine', 8.5)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Rouge Petard (Aramon) — 125ml', 'wine', 7.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Rouge Petard (Aramon) — Bottle', 'wine', 39.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Lentsch Grüner Veltliner — 125ml', 'wine', 8.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Lentsch Grüner Veltliner — Bottle', 'wine', 40.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Spicy Cucumber Margarita', 'cocktail', 11.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Mezcal Martinez', 'cocktail', 12.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Caipirinha', 'cocktail', 11.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Royal Flush', 'cocktail', 10.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Watermelon Daiquiri', 'cocktail', 10.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Lagerita / Tequila Michelada', 'cocktail', 10.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Any Classic (avg)', 'cocktail', 11.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Vermut + Soda (double, tall)', 'spritz', 7.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Cynar + Soda', 'spritz', 7.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Amaro + Soda', 'spritz', 7.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Campari + Soda', 'spritz', 7.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Limoncello + Soda', 'spritz', 7.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Ranch Water', 'spritz', 7.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Kalimoxto', 'spritz', 8.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Beericano', 'spritz', 10.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Hugo Spritz', 'spritz', 11.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Sambuca (shot)', 'shot', 4.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Devils Lobotomy', 'shot', 6.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Baby Guinness', 'shot', 6.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Kombucha', 'soft', 4.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Ting', 'soft', 3.5)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Red Bull', 'soft', 3.5)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Ginger Beer', 'soft', 3.5)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Fanta', 'soft', 3.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Gilda (each)', 'snack', 2.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Gilda (6 for £10)', 'snack', 10.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Crisps', 'snack', 1.7)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Nuts', 'snack', 1.5)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Olives', 'snack', 3.5)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Espresso Martini', 'cocktail', 11.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Classic Margarita', 'cocktail', 11.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Tommy''s Margarita', 'cocktail', 11.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Mezcal Margarita', 'cocktail', 12.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Paloma', 'cocktail', 11.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Whiskey Sour', 'cocktail', 11.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Amaretto Sour', 'cocktail', 11.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Negroni', 'cocktail', 11.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Classic / Dirty Martini', 'cocktail', 11.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Cola Soda / Spritzer', 'cocktail', 11.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Mango Mojito', 'cocktail', 11.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Classic Mojito', 'cocktail', 11.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Old Fashioned', 'cocktail', 11.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Aperol Spritz (single)', 'spritz', 9.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Lillet Spritz', 'spritz', 9.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('White Wine Spritzer', 'spritz', 8.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Dark & Stormy (Jug)', 'jug', 28.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Aperol Spritz - Jug', 'jug', 30.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Royal Flush (Jug)', 'jug', 32.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Mocktail Mojito', 'mocktail', 6.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
insert into bar_menu_items (name, category, sell_price) values ('Mocktail Royal Flush', 'mocktail', 6.0)
  on conflict ((lower(name))) do update set sell_price = excluded.sell_price, category = excluded.category, active = true;
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Camden Hells — Pint'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 568.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Camden Hells — Pint') and lower(p.name) = lower('Camden Hells');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Camden Hells — Half'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 284.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Camden Hells — Half') and lower(p.name) = lower('Camden Hells');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Camden Hells — Jug'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 2272.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Camden Hells — Jug') and lower(p.name) = lower('Camden Hells');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Camden Stout'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 568.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Camden Stout') and lower(p.name) = lower('Camden Stout');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Camden Stout — Half'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 284.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Camden Stout — Half') and lower(p.name) = lower('Camden Stout');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Five Points XPA — Pint'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 568.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Five Points XPA — Pint') and lower(p.name) = lower('Five Points XPA');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Five Points XPA — Half'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 284.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Five Points XPA — Half') and lower(p.name) = lower('Five Points XPA');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Umbrella Cider — Pint'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 568.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Umbrella Cider — Pint') and lower(p.name) = lower('Umbrella Apple Cider (keg)');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Umbrella Cider — Half'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 284.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Umbrella Cider — Half') and lower(p.name) = lower('Umbrella Apple Cider (keg)');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Corona'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 1 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Corona') and lower(p.name) = lower('Corona');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Asahi'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 1 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Asahi') and lower(p.name) = lower('Asahi');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Budweiser'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 1 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Budweiser') and lower(p.name) = lower('Budweiser');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Corona 0%'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 1 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Corona 0%') and lower(p.name) = lower('Corona 0%');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Big Drop Citra IPA 0.5%'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 1 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Big Drop Citra IPA 0.5%') and lower(p.name) = lower('Big Drop Citra IPA 0.5%');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Lucky Saint 0.5%'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 1 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Lucky Saint 0.5%') and lower(p.name) = lower('Lucky Saint 0.5%');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Cloudwater Fresh AF 0.5%'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 1 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Cloudwater Fresh AF 0.5%') and lower(p.name) = lower('Fresh Non-Alc');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Oliver''s Fine Cider'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 1 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Oliver''s Fine Cider') and lower(p.name) = lower('Oliver''s Fine Cider (bottle)');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Cheery Breeze Sour 4.5%'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 1 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Cheery Breeze Sour 4.5%') and lower(p.name) = lower('Cherry Sour');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Piccadilly Pilsner 4.2%'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 1 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Piccadilly Pilsner 4.2%') and lower(p.name) = lower('Piccadilly Pilsner GF');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Fresh AF Hazy IPA 0.5%'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 1 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Fresh AF Hazy IPA 0.5%') and lower(p.name) = lower('Fresh Non-Alc');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Big Drop Paradiso Citra 0.5%'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 1 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Big Drop Paradiso Citra 0.5%') and lower(p.name) = lower('Big Drop Citra IPA 0.5%');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Blanco Blanco — 125ml'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 125.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Blanco Blanco — 125ml') and lower(p.name) = lower('Blanco Blanco (white)');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Blanco Blanco — Bottle'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 750.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Blanco Blanco — Bottle') and lower(p.name) = lower('Blanco Blanco (white)');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Los Conejos Malditos — 125ml'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 125.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Los Conejos Malditos — 125ml') and lower(p.name) = lower('Los Conejos Tinto (red)');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Los Conejos Malditos — Bottle'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 750.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Los Conejos Malditos — Bottle') and lower(p.name) = lower('Los Conejos Tinto (red)');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Doom Juice Rose'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 125.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Doom Juice Rose') and lower(p.name) = lower('Doom Juice Rosé');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Doom Juice Rosé — Bottle'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 750.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Doom Juice Rosé — Bottle') and lower(p.name) = lower('Doom Juice Rosé');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Top Cuvee Orange — 125ml'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 125.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Top Cuvee Orange — 125ml') and lower(p.name) = lower('Top Cuvée House Orange');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Top Cuvee Orange — Bottle'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 750.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Top Cuvee Orange — Bottle') and lower(p.name) = lower('Top Cuvée House Orange');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Favonius Orange — Bottle'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 750.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Favonius Orange — Bottle') and lower(p.name) = lower('Favonius Orange');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Doom Juice Rouge — 125ml'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 125.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Doom Juice Rouge — 125ml') and lower(p.name) = lower('Doom Juice Rouge');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Doom Juice Rouge — Bottle'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 750.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Doom Juice Rouge — Bottle') and lower(p.name) = lower('Doom Juice Rouge');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Beaujolais Nouveau'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 750.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Beaujolais Nouveau') and lower(p.name) = lower('Beaujolais Nouveau');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Chin Chin Vinho Verde — 125ml'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 125.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Chin Chin Vinho Verde — 125ml') and lower(p.name) = lower('Chin Chin Vinho Verde');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Chin Chin Vinho Verde — Bottle'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 750.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Chin Chin Vinho Verde — Bottle') and lower(p.name) = lower('Chin Chin Vinho Verde');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Cueva Nueva Vermut — Double (50ml)'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 50.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Cueva Nueva Vermut — Double (50ml)') and lower(p.name) = lower('Cueva Nueva Vermut (500ml)');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Cueva Nueva Vermut — Bottle (500ml)'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 500.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Cueva Nueva Vermut — Bottle (500ml)') and lower(p.name) = lower('Cueva Nueva Vermut (500ml)');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Prosecco — 125ml flute'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 125.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Prosecco — 125ml flute') and lower(p.name) = lower('Prosecco 750ml (NV Via Vai)');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Prosecco'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 750.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Prosecco') and lower(p.name) = lower('Prosecco 750ml (NV Via Vai)');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Mini Prosecco 20cl'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 200.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Mini Prosecco 20cl') and lower(p.name) = lower('Mini Prosecco 20cl');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Rouge Petard (Aramon) — 125ml'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 125.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Rouge Petard (Aramon) — 125ml') and lower(p.name) = lower('Rouge Petard');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Rouge Petard (Aramon) — Bottle'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 750.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Rouge Petard (Aramon) — Bottle') and lower(p.name) = lower('Rouge Petard');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Lentsch Grüner Veltliner — 125ml'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 125.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Lentsch Grüner Veltliner — 125ml') and lower(p.name) = lower('Lentsch Grüner Veltliner');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Lentsch Grüner Veltliner — Bottle'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 750.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Lentsch Grüner Veltliner — Bottle') and lower(p.name) = lower('Lentsch Grüner Veltliner');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Spicy Cucumber Margarita'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 50.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Spicy Cucumber Margarita') and lower(p.name) = lower('Cazcabel Reposado');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 25.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Spicy Cucumber Margarita') and lower(p.name) = lower('Fresh lime juice');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 12.5 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Spicy Cucumber Margarita') and lower(p.name) = lower('Agave syrup');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Mezcal Martinez'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 35.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Mezcal Martinez') and lower(p.name) = lower('Vida Mezcal');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 25.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Mezcal Martinez') and lower(p.name) = lower('Amaro Montenegro');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 5.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Mezcal Martinez') and lower(p.name) = lower('Top Cuvée Sweet Vermouth');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Caipirinha'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 50.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Caipirinha') and lower(p.name) = lower('Velho Barreiro Cachaça');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 25.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Caipirinha') and lower(p.name) = lower('Fresh lime juice');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 25.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Caipirinha') and lower(p.name) = lower('Sugar syrup 1:1');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Royal Flush'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 25.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Royal Flush') and lower(p.name) = lower('Havana Especial');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 12.5 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Royal Flush') and lower(p.name) = lower('Triple Sec');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 12.5 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Royal Flush') and lower(p.name) = lower('Wray & Nephew Overproof');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 150.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Royal Flush') and lower(p.name) = lower('Eager Pineapple');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 10.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Royal Flush') and lower(p.name) = lower('Monin Grenadine');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Watermelon Daiquiri'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 50.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Watermelon Daiquiri') and lower(p.name) = lower('Watermelon');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 12.5 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Watermelon Daiquiri') and lower(p.name) = lower('Fresh lime juice');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 20.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Watermelon Daiquiri') and lower(p.name) = lower('Sugar syrup 1:1');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 35.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Watermelon Daiquiri') and lower(p.name) = lower('Havana Club 3yr');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 1.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Watermelon Daiquiri') and lower(p.name) = lower('Ms Better''s Foamer');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 3.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Watermelon Daiquiri') and lower(p.name) = lower('Mint');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Lagerita / Tequila Michelada'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 25.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Lagerita / Tequila Michelada') and lower(p.name) = lower('Cazcabel Blanco');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 25.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Lagerita / Tequila Michelada') and lower(p.name) = lower('Fresh lime juice');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 284.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Lagerita / Tequila Michelada') and lower(p.name) = lower('Camden Hells');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Any Classic (avg)'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 50.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Any Classic (avg)') and lower(p.name) = lower('Jameson');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 25.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Any Classic (avg)') and lower(p.name) = lower('Fresh lemon juice');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 15.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Any Classic (avg)') and lower(p.name) = lower('Sugar syrup 1:1');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Vermut + Soda (double, tall)'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 50.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Vermut + Soda (double, tall)') and lower(p.name) = lower('El Bandarra Vermut');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Cynar + Soda'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 50.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Cynar + Soda') and lower(p.name) = lower('Cynar');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Amaro + Soda'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 50.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Amaro + Soda') and lower(p.name) = lower('Amaro Montenegro');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Campari + Soda'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 50.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Campari + Soda') and lower(p.name) = lower('Campari');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Limoncello + Soda'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 50.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Limoncello + Soda') and lower(p.name) = lower('Limoncello');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Ranch Water'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 25.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Ranch Water') and lower(p.name) = lower('Cazcabel Blanco');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 25.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Ranch Water') and lower(p.name) = lower('Fresh lime juice');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Kalimoxto'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 125.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Kalimoxto') and lower(p.name) = lower('House red (Kalimotxo)');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 200.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Kalimoxto') and lower(p.name) = lower('Coke');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Beericano'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 284.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Beericano') and lower(p.name) = lower('Camden Hells');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 25.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Beericano') and lower(p.name) = lower('Campari');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 25.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Beericano') and lower(p.name) = lower('El Bandarra Vermut');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Hugo Spritz'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 35.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Hugo Spritz') and lower(p.name) = lower('St Germain');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 125.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Hugo Spritz') and lower(p.name) = lower('Prosecco 750ml (NV Via Vai)');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Sambuca (shot)'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 25.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Sambuca (shot)') and lower(p.name) = lower('Antica Sambuca');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Devils Lobotomy'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 12.5 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Devils Lobotomy') and lower(p.name) = lower('Devil\''s Botany Chocolate 24%');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 12.5 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Devils Lobotomy') and lower(p.name) = lower('Camden Stout');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Baby Guinness'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 25.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Baby Guinness') and lower(p.name) = lower('Kahlúa');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 10.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Baby Guinness') and lower(p.name) = lower('Baileys');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Kombucha'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 1 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Kombucha') and lower(p.name) = lower('Kombucha');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Ting'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 1 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Ting') and lower(p.name) = lower('Ting');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Red Bull'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 1 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Red Bull') and lower(p.name) = lower('Red Bull');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Ginger Beer'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 1 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Ginger Beer') and lower(p.name) = lower('Old Jamaica Ginger Beer');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Fanta'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 1 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Fanta') and lower(p.name) = lower('Fanta');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Gilda (each)'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 1 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Gilda (each)') and lower(p.name) = lower('Gilda');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Gilda (6 for £10)'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 6 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Gilda (6 for £10)') and lower(p.name) = lower('Gilda');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Crisps'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 1 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Crisps') and lower(p.name) = lower('Crisps');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Nuts'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 1 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Nuts') and lower(p.name) = lower('Nuts');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Olives'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 0.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Olives') and lower(p.name) = lower('Olives');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Espresso Martini'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 30.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Espresso Martini') and lower(p.name) = lower('Absolut Blue');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 25.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Espresso Martini') and lower(p.name) = lower('Kahlúa');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 30.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Espresso Martini') and lower(p.name) = lower('Coffee extract');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 7.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Espresso Martini') and lower(p.name) = lower('Sugar syrup 1:1');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Classic Margarita'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 50.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Classic Margarita') and lower(p.name) = lower('Cazcabel Blanco');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 20.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Classic Margarita') and lower(p.name) = lower('Triple Sec');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 25.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Classic Margarita') and lower(p.name) = lower('Fresh lime juice');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Tommy''s Margarita'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 50.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Tommy''s Margarita') and lower(p.name) = lower('Cazcabel Reposado');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 40.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Tommy''s Margarita') and lower(p.name) = lower('Fresh lime juice');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 15.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Tommy''s Margarita') and lower(p.name) = lower('Agave syrup');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Mezcal Margarita'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 35.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Mezcal Margarita') and lower(p.name) = lower('Vida Mezcal');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 15.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Mezcal Margarita') and lower(p.name) = lower('Triple Sec');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 25.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Mezcal Margarita') and lower(p.name) = lower('Fresh lime juice');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Paloma'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 50.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Paloma') and lower(p.name) = lower('Cazcabel Blanco');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 10.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Paloma') and lower(p.name) = lower('Fresh lime juice');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 10.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Paloma') and lower(p.name) = lower('Agave syrup');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 0.01 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Paloma') and lower(p.name) = lower('Eager Grapefruit');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 0.15 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Paloma') and lower(p.name) = lower('Ting');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Whiskey Sour'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 50.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Whiskey Sour') and lower(p.name) = lower('Four Roses Bourbon');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 30.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Whiskey Sour') and lower(p.name) = lower('Fresh lemon juice');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 10.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Whiskey Sour') and lower(p.name) = lower('Sugar syrup 1:1');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 0.5 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Whiskey Sour') and lower(p.name) = lower('Angostura bitters');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 2.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Whiskey Sour') and lower(p.name) = lower('Ms Better''s Foamer');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Amaretto Sour'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 75.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Amaretto Sour') and lower(p.name) = lower('Disaronno Amaretto');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 30.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Amaretto Sour') and lower(p.name) = lower('Fresh lemon juice');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 0.5 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Amaretto Sour') and lower(p.name) = lower('Angostura bitters');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 2.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Amaretto Sour') and lower(p.name) = lower('Ms Better''s Foamer');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Negroni'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 25.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Negroni') and lower(p.name) = lower('Hanbury London Dry (house)');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 25.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Negroni') and lower(p.name) = lower('Campari');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 25.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Negroni') and lower(p.name) = lower('Cocchi Americano');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Classic / Dirty Martini'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 50.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Classic / Dirty Martini') and lower(p.name) = lower('Absolut Blue');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 10.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Classic / Dirty Martini') and lower(p.name) = lower('Martini Dry');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Cola Soda / Spritzer'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 15.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Cola Soda / Spritzer') and lower(p.name) = lower('Kraken Black Spiced');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 25.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Cola Soda / Spritzer') and lower(p.name) = lower('Velvet Falernum');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 30.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Cola Soda / Spritzer') and lower(p.name) = lower('Amaro Montenegro');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 75.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Cola Soda / Spritzer') and lower(p.name) = lower('Prosecco 750ml (NV Via Vai)');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Mango Mojito'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 50.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Mango Mojito') and lower(p.name) = lower('Havana Especial');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 40.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Mango Mojito') and lower(p.name) = lower('Funkin Mango purée');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 5.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Mango Mojito') and lower(p.name) = lower('Funkin Passion Fruit purée');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 7.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Mango Mojito') and lower(p.name) = lower('Mint');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Classic Mojito'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 50.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Classic Mojito') and lower(p.name) = lower('Havana Especial');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 25.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Classic Mojito') and lower(p.name) = lower('Fresh lime juice');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 10.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Classic Mojito') and lower(p.name) = lower('Sugar syrup 1:1');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 7.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Classic Mojito') and lower(p.name) = lower('Mint');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Old Fashioned'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 50.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Old Fashioned') and lower(p.name) = lower('Four Roses Bourbon');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 10.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Old Fashioned') and lower(p.name) = lower('Sugar syrup 1:1');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 1.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Old Fashioned') and lower(p.name) = lower('Angostura bitters');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Aperol Spritz (single)'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 50.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Aperol Spritz (single)') and lower(p.name) = lower('Aperol');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 75.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Aperol Spritz (single)') and lower(p.name) = lower('Prosecco 750ml (NV Via Vai)');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Lillet Spritz'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 70.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Lillet Spritz') and lower(p.name) = lower('Lillet Rosé');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 5.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Lillet Spritz') and lower(p.name) = lower('Fresh lemon juice');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 50.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Lillet Spritz') and lower(p.name) = lower('Lemonade');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('White Wine Spritzer'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 100.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('White Wine Spritzer') and lower(p.name) = lower('Blanco Blanco (white)');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 100.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('White Wine Spritzer') and lower(p.name) = lower('Lemonade');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Dark & Stormy (Jug)'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 150.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Dark & Stormy (Jug)') and lower(p.name) = lower('Havana Club 7yr');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 45.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Dark & Stormy (Jug)') and lower(p.name) = lower('Fresh lime juice');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 2 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Dark & Stormy (Jug)') and lower(p.name) = lower('Old Jamaica Ginger Beer');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 3.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Dark & Stormy (Jug)') and lower(p.name) = lower('Angostura bitters');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Aperol Spritz - Jug'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 150.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Aperol Spritz - Jug') and lower(p.name) = lower('Aperol');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 500.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Aperol Spritz - Jug') and lower(p.name) = lower('Prosecco 750ml (NV Via Vai)');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Royal Flush (Jug)'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 120.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Royal Flush (Jug)') and lower(p.name) = lower('Havana Especial');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 60.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Royal Flush (Jug)') and lower(p.name) = lower('Triple Sec');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 100.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Royal Flush (Jug)') and lower(p.name) = lower('Eager Pineapple');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 100.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Royal Flush (Jug)') and lower(p.name) = lower('Eager Orange');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 30.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Royal Flush (Jug)') and lower(p.name) = lower('Monin Grenadine');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Mocktail Mojito'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 50.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Mocktail Mojito') and lower(p.name) = lower('Fresh lime juice');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 10.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Mocktail Mojito') and lower(p.name) = lower('Sugar syrup 1:1');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 7.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Mocktail Mojito') and lower(p.name) = lower('Mint');
delete from bar_recipe_lines where menu_item_id = (select id from bar_menu_items where lower(name) = lower('Mocktail Royal Flush'));
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 100.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Mocktail Royal Flush') and lower(p.name) = lower('Eager Pineapple');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 100.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Mocktail Royal Flush') and lower(p.name) = lower('Eager Orange');
insert into bar_recipe_lines (menu_item_id, product_id, qty_base)
  select m.id, p.id, 15.0 from bar_menu_items m, bar_products p
  where lower(m.name) = lower('Mocktail Royal Flush') and lower(p.name) = lower('Monin Grenadine');
commit;
