-- Food self-order + kitchen tickets (On A Roll food truck) — Aug 2026.
-- One row per customer order placed (and paid for) on the order page. The kitchen
-- display (/ops → Kitchen → 🎫 Orders) lists live ones, and marking an order READY
-- fires the "food ready" SMS via the food-order edge function (reuses Twilio).
-- RLS ON with no policies = service-role only (the edge function uses the service key).

create table if not exists food_orders (
  id            uuid primary key default gen_random_uuid(),
  order_no      int generated by default as identity,   -- short human number shown to staff + customer
  created_at    timestamptz not null default now(),
  customer_name text,
  customer_phone text,
  items         jsonb not null default '[]'::jsonb,      -- [{ name, qty, price_pence, options:[{name,price_pence}] }]
  total_pence   int not null default 0,
  status        text not null default 'new'
                  check (status in ('new','preparing','ready','collected','cancelled')),
  paid          boolean not null default false,
  payment_ref   text,                                    -- Stripe payment intent id
  allergen_note text,                                    -- customer-entered allergy note (shown on the ticket)
  voucher_code  text,                                    -- set if a bundle beer voucher was issued
  ready_at      timestamptz,
  ready_by      text,
  collected_at  timestamptz
);

create index if not exists idx_food_orders_live
  on food_orders (created_at)
  where status in ('new','preparing','ready');

alter table food_orders enable row level security;
