#!/usr/bin/env python3
"""Generate seed SQL for the BAR stock system from the existing data files.

Deterministic — parses src/ops/data/{stockCheck,suppliers}.js with regexes and
maps each item's written unit onto the schema's base units. NOTHING is guessed:
where a pack size isn't stated the product is seeded as whole units ('each'),
which counts and orders correctly and simply can't be costed per-ml until
someone supplies the size. Those land in the NEEDS-A-SIZE list.
"""
import re, sys, collections

SC = open('src/ops/data/stockCheck.js').read()
SUP = open('src/ops/data/suppliers.js').read()

def q(s): return "'" + (s or '').replace("'", "''") + "'"

# ── unit vocabulary → (base_unit, order_unit, order_to_base, count_unit, count_to_base)
# ml  = we pour it   ·   g = we weigh it   ·   each = we serve/count it whole
ML, G, EA = 'ml', 'g', 'each'
UNITS = {
  '700ml':             (ML,'bottle',700,'bottle',700),
  '500ml':             (ML,'bottle',500,'bottle',500),
  '750ml':             (ML,'bottle',750,'bottle',750),
  '1L':                (ML,'bottle',1000,'bottle',1000),
  '120ml':             (ML,'bottle',120,'bottle',120),
  '2.1L refill':       (ML,'refill',2100,'refill',2100),
  '7L BIB':            (ML,'BIB',7000,'BIB',7000),
  '30L keg':           (ML,'keg',30000,'keg',30000),
  '50L keg':           (ML,'keg',50000,'keg',50000),
  'bottle':            (ML,'bottle',750,'bottle',750),      # wine group only — standard 75cl
  '1kg pouch':         (G,'pouch',1000,'pouch',1000),
  'kg bag':            (G,'bag',1000,'bag',1000),
  'kg':                (G,'kg',1000,'kg',1000),
  '20kg case':         (G,'case',20000,'kg',1000),
  '100g bunch':        (G,'bunch',100,'bunch',100),
  'case (24 × 330ml)': (EA,'case',24,'bottle',1),
  'case (×24)':        (EA,'case',24,'unit',1),
  'case (×36)':        (EA,'case',36,'unit',1),
  'case (×60)':        (EA,'case',60,'unit',1),
  'case (8 × 1L)':     (EA,'case',8,'carton',1),
}
# Stated as a container with no size — count them whole, flag for a size later.
WHOLE = {'case','each','box','jar','tub','tub / box','carton','cylinder','keg'}

# Pack sizes the founder confirmed on 17 Aug 2026, keyed by product name. These
# beat the written unit, so re-running this seeder reproduces the live database
# instead of reverting these lines to whole units.
#   name -> (base_unit, order_unit, order_to_base, count_unit, count_to_base)
CONFIRMED = {
  'Eager Pineapple':            (ML,'case',8000,'carton',1000),
  'Eager Cloudy Apple':         (ML,'case',8000,'carton',1000),
  'Eager Cranberry':            (ML,'case',8000,'carton',1000),
  'Eager Orange':               (ML,'case',8000,'carton',1000),
  'Umbrella Apple Cider (keg)': (ML,'keg',50000,'keg',50000),
  'Lemons':                     (EA,'case',30,'each',1),
  # "All beers are in packs of 24" (founder)
  'Big Drop Citra IPA 0.5%':    (EA,'case',24,'bottle',1),
  'Piccadilly Pilsner GF':      (EA,'case',24,'bottle',1),
  'Cherry Sour':                (EA,'case',24,'bottle',1),
  'Fresh Non-Alc':              (EA,'case',24,'bottle',1),
}
# Off the menu — seeded inactive rather than dropped, so any history survives.
RETIRED = {'Kombucha'}

KIND = {                       # group label prefix → product kind
  'Fruit & perishables': 'fresh', 'Snacks': 'other', 'Gas': 'other',
}
def kind_for(group):
    for k,v in KIND.items():
        if group.startswith(k): return v
    return 'drink'

# ── parse the sheet, keeping each item's group ──────────────────────────────
rows, group = [], None
pat = re.compile(r"label:\s*'([^']+)'|\{\s*key:\s*'([^']+)',\s*name:\s*([\"'])(.*?)\3,\s*unit:\s*([\"'])(.*?)\5(?:,\s*supplier:\s*([\"'])(.*?)\7)?")
for m in pat.finditer(SC):
    if m.group(1): group = m.group(1); continue
    rows.append(dict(key=m.group(2), name=m.group(4), unit=m.group(6),
                     supplier=m.group(8), group=group))

# ── suppliers ───────────────────────────────────────────────────────────────
sup_names = re.findall(r"\n\s*name:\s*([\"'])(.*?)\1", SUP)
suppliers = sorted({n for _,n in sup_names})
for r in rows:                                   # names used on the sheet too
    if r['supplier']: suppliers.append(r['supplier'])
suppliers = sorted(set(suppliers))

out = ["-- Seed generated by scripts/seed_bar.py — safe to re-run (idempotent).", "begin;"]
for s in suppliers:
    out.append(f"insert into bar_suppliers (name) values ({q(s)}) on conflict (name) do nothing;")

needs_size, seeded = [], 0
for r in rows:
    u = r['unit']
    if r['name'] in CONFIRMED:
        base, ou, otb, cu, ctb = CONFIRMED[r['name']]
    elif u in UNITS:
        base, ou, otb, cu, ctb = UNITS[u]
    elif u in WHOLE:
        base, ou, otb, cu, ctb = EA, u.split(' /')[0], 1, u.split(' /')[0], 1
        needs_size.append((r['group'], r['name'], u))
    else:
        print(f"!! unmapped unit {u!r} on {r['name']!r}", file=sys.stderr); continue
    cat = r['group'].split('—')[-1].strip() if '—' in r['group'] else r['group']
    area = 'Cellar' if 'keg' in u.lower() or 'Draught' in r['group'] else \
           'Fridge' if 'Fruit' in r['group'] or 'Juice' in r['group'] else 'Back bar'
    sup = f"(select id from bar_suppliers where name = {q(r['supplier'])})" if r['supplier'] else 'null'
    out.append(
      "insert into bar_products (name,kind,category,source,base_unit,order_unit,order_to_base,"
      "count_unit,count_to_base,count_area,supplier_id,notes) values ("
      f"{q(r['name'])},{q(kind_for(r['group']))},{q(cat)},'bought',{q(base)},{q(ou)},{otb},"
      f"{q(cu)},{ctb},{q(area)},{sup},{q('seeded from stock sheet · unit written as: '+u)}) "
      "on conflict (lower(name)) do nothing;")
    if r['name'] in RETIRED:
        out.append(f"update bar_products set active=false where lower(name)=lower({q(r['name'])});")
    seeded += 1

out.append("commit;")
open('supabase/bar_seed.sql','w').write("\n".join(out) + "\n")

print(f"suppliers: {len(suppliers)}")
print(f"products seeded: {seeded} of {len(rows)}")
print(f"\nNEEDS A PACK SIZE ({len(needs_size)}) — counted as whole units until confirmed:")
for g,n,u in needs_size: print(f"   {g[:30]:32} {n[:34]:36} '{u}'")
